name: git-hub-actions-test
on: [push]
jobs:
  set-up-ubuntu:
    runs-on: ubuntu-latest
    steps:       
      - name: print statement
        run: echo "hello world..."
      - name: get java version
        run: java -version
      - name: get maven version
        run: mvn -version
  dependent-job:
    runs-on: windows-latest
    needs: set-up-ubuntu
    steps: 
      - name: write string
        run: Write-Output "printing in powershell."
