name: workflow-command
on: [push]
jobs:
  error-printing:
    runs-on: ubuntu-latest
    steps: 
      - name: setting error message
        run: echo "::error::missing semicolon;"
      - name: setting error message with param
        run: echo "::error title=error title, file=app.js, line=2::missing semicolon"
      - name: setting debug message with param
        run: echo "::debug title=error title, file=app.js, line=2::missing semicolon"
      - name: setting warning message with param
        run: echo "::warning title=error title, file=app.js, line=2::missing semicolon"
      - name: setting notice message with param
        run: echo "::notice title=error title, file=app.js, line=2::missing semicolon"
      - name: add mask to variable
        run: "::add-mask::secret string"
      - name: print secret variable
        run: echo "secret string."
        
  
  